 Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0be2609ba883822ec # Amazon Linux AMI in US East (N. Virginia)
      Tags:
        - Key: Name
          Value: demoEC2
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
